#!/usr/bin/env bash
# deploy.sh — build & host sharemarketplace on Linux (Docker + Caddy)
#
# Examples:
#   ./deploy.sh up --domain example.com --subdomain marketplace --email you@example.com
#   ./deploy.sh up --host marketplace.example.com --email you@example.com
#   ./deploy.sh up --wildcard example.com --email you@example.com
#   ./deploy.sh down
#   ./deploy.sh logs
#   ./deploy.sh status
#   ./deploy.sh dns-hint
#
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT_DIR"

COMPOSE="docker compose"
STATE_DIR="$ROOT_DIR/deploy/state"
ENV_FILE="$ROOT_DIR/.env"
CADDY_ACTIVE="$ROOT_DIR/deploy/caddy/Caddyfile"

MODE="subdomain" # subdomain | host | wildcard | local
DOMAIN=""
SUBDOMAIN="marketplace"
HOST=""
EMAIL=""
USE_CADDY=1
CMD="${1:-}"
shift || true

usage() {
  cat <<'EOF'
Usage:
  ./deploy.sh local            Build + run API only on :8787 (no domain / no Caddy)
  ./deploy.sh up [options]     Build + run with Caddy TLS (needs domain)
  ./deploy.sh down             Stop containers
  ./deploy.sh restart          Restart stack
  ./deploy.sh logs [-f]        Tail logs
  ./deploy.sh status           Health + compose ps
  ./deploy.sh build            Build image only
  ./deploy.sh dns-hint         Print DNS records for the configured host
  ./deploy.sh url              Print editor MARKETPLACE_URL

Options for up:
  --domain DOMAIN              Apex domain (example.com)
  --subdomain NAME             Subdomain label (default: marketplace)
  --host FQDN                  Explicit hostname (marketplace.example.com)
  --wildcard DOMAIN            Serve apex + *.DOMAIN with on-demand TLS
  --email EMAIL                ACME / Let's Encrypt contact email
  --no-caddy                   Same as ./deploy.sh local (API on :8787 only)

DNS:
  Subdomain mode → A/AAAA record for marketplace.example.com → this server
  Wildcard mode  → A/AAAA for example.com AND *.example.com → this server
                   (on-demand certs; SHAREMARKETPLACE_TLS_ALLOW_SUFFIX=.example.com)
EOF
}

die() { echo "error: $*" >&2; exit 1; }

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "missing required command: $1"
}

write_local_env() {
  mkdir -p "$STATE_DIR" "$(dirname "$CADDY_ACTIVE")"
  # Keep a harmless default Caddyfile for compose validation
  if [[ ! -f "$CADDY_ACTIVE" ]]; then
    cp "$ROOT_DIR/deploy/caddy/Caddyfile.subdomain" "$CADDY_ACTIVE" 2>/dev/null || true
  fi
  cat >"$ENV_FILE" <<EOF
# Generated by deploy.sh local — $(date -u +%Y-%m-%dT%H:%M:%SZ)
MARKETPLACE_HOST=localhost
MARKETPLACE_BASE_DOMAIN=localhost
MARKETPLACE_PUBLISH=8787
ACME_EMAIL=
RUST_LOG=sharemarketplace=info,tower_http=info
SHAREMARKETPLACE_TLS_ALLOW_HOST=
SHAREMARKETPLACE_TLS_ALLOW_SUFFIX=
EOF
  rm -f "$ROOT_DIR/docker-compose.override.yml"
  echo "local" >"$STATE_DIR/mode"
  echo "localhost" >"$STATE_DIR/host"
  echo "localhost" >"$STATE_DIR/base_domain"
}

parse_up_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --domain) DOMAIN="${2:-}"; shift 2 ;;
      --subdomain) SUBDOMAIN="${2:-}"; shift 2 ;;
      --host) MODE="host"; HOST="${2:-}"; shift 2 ;;
      --wildcard) MODE="wildcard"; DOMAIN="${2:-}"; shift 2 ;;
      --email) EMAIL="${2:-}"; shift 2 ;;
      --no-caddy) USE_CADDY=0; shift ;;
      -h|--help) usage; exit 0 ;;
      *) die "unknown option: $1" ;;
    esac
  done

  if [[ "$USE_CADDY" -eq 0 ]]; then
    MODE="local"
    write_local_env
    echo "Configured: local API on :8787 (no Caddy)"
    return
  fi

  if [[ "$MODE" == "host" ]]; then
    [[ -n "$HOST" ]] || die "--host requires a value"
  elif [[ "$MODE" == "wildcard" ]]; then
    [[ -n "$DOMAIN" ]] || die "--wildcard requires a domain"
    HOST="$DOMAIN"
  else
    if [[ -n "$HOST" ]]; then
      :
    elif [[ -n "$DOMAIN" ]]; then
      HOST="${SUBDOMAIN}.${DOMAIN}"
    else
      die "provide --domain/--subdomain, --host, --wildcard, or use: ./deploy.sh local"
    fi
    MODE="subdomain"
  fi

  if [[ -z "$EMAIL" ]]; then
    echo "warning: --email not set; Caddy will still attempt ACME (set ACME_EMAIL in .env)" >&2
  fi

  mkdir -p "$STATE_DIR" "$(dirname "$CADDY_ACTIVE")"

  local base_domain="$DOMAIN"
  if [[ -z "$base_domain" && "$HOST" == *.* ]]; then
    base_domain="${HOST#*.}"
  fi

  local tls_suffix=""
  local tls_host=""
  local caddy_template=""

  if [[ "$MODE" == "wildcard" ]]; then
    caddy_template="$ROOT_DIR/deploy/caddy/Caddyfile.wildcard"
    tls_suffix=".${DOMAIN}"
    tls_host="$DOMAIN"
    base_domain="$DOMAIN"
  else
    caddy_template="$ROOT_DIR/deploy/caddy/Caddyfile.subdomain"
    tls_host="$HOST"
    tls_suffix=""
  fi

  [[ -f "$caddy_template" ]] || die "missing Caddy template: $caddy_template"
  cp "$caddy_template" "$CADDY_ACTIVE"

  cat >"$ENV_FILE" <<EOF
# Generated by deploy.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)
MARKETPLACE_HOST=${HOST}
MARKETPLACE_BASE_DOMAIN=${base_domain}
MARKETPLACE_PUBLISH=8787
ACME_EMAIL=${EMAIL}
RUST_LOG=sharemarketplace=info,tower_http=info
SHAREMARKETPLACE_TLS_ALLOW_HOST=${tls_host}
SHAREMARKETPLACE_TLS_ALLOW_SUFFIX=${tls_suffix}
EOF

  rm -f "$ROOT_DIR/docker-compose.override.yml"

  echo "$MODE" >"$STATE_DIR/mode"
  echo "$HOST" >"$STATE_DIR/host"
  echo "$base_domain" >"$STATE_DIR/base_domain"

  echo "Configured:"
  echo "  mode:   $MODE"
  echo "  host:   $HOST"
  echo "  email:  ${EMAIL:-'(unset)'}"
  if [[ "$MODE" == "wildcard" ]]; then
    echo "  tls:    on-demand for ${DOMAIN} and *.${DOMAIN}"
  fi
}

compose() {
  local files=(-f docker-compose.yml)
  if [[ -f docker-compose.override.yml ]]; then
    files+=(-f docker-compose.override.yml)
  fi
  if [[ -f "$ENV_FILE" ]]; then
    $COMPOSE --env-file "$ENV_FILE" "${files[@]}" "$@"
  else
    $COMPOSE "${files[@]}" "$@"
  fi
}

print_dns_hint() {
  local host="${1:-}"
  local base="${2:-}"
  local mode="${3:-subdomain}"
  if [[ -z "$host" && -f "$STATE_DIR/host" ]]; then
    host="$(cat "$STATE_DIR/host")"
  fi
  if [[ -z "$base" && -f "$STATE_DIR/base_domain" ]]; then
    base="$(cat "$STATE_DIR/base_domain")"
  fi
  if [[ -z "$mode" && -f "$STATE_DIR/mode" ]]; then
    mode="$(cat "$STATE_DIR/mode")"
  fi
  [[ -n "$host" ]] || die "no host configured; run ./deploy.sh up first"

  local ip
  ip="$(curl -4 -fsS --max-time 5 https://ifconfig.me 2>/dev/null || true)"
  [[ -n "$ip" ]] || ip="<THIS_SERVER_PUBLIC_IPV4>"

  echo "DNS records (point at this VPS):"
  if [[ "$mode" == "wildcard" ]]; then
    echo "  A     ${base}     ${ip}"
    echo "  A     *.${base}   ${ip}   # if your DNS supports wildcard A"
    echo "  AAAA  ${base}     <ipv6>  # optional"
    echo "  AAAA  *.${base}   <ipv6>  # optional"
  else
    echo "  A     ${host}   ${ip}"
    echo "  AAAA  ${host}   <ipv6>  # optional"
  fi
  echo
  echo "Editor setting:"
  echo "  MARKETPLACE_URL=https://${host}"
}

cmd_local() {
  need_cmd docker
  docker compose version >/dev/null 2>&1 || die "docker compose plugin required"
  write_local_env
  compose build
  compose up -d marketplace
  echo
  echo "API listening on http://127.0.0.1:8787"
  echo "Health: curl -fsS http://127.0.0.1:8787/v1/health"
  echo "Editor MARKETPLACE_URL=http://127.0.0.1:8787"
  echo
  echo "Logs: ./deploy.sh logs -f"
}

cmd_up() {
  need_cmd docker
  docker compose version >/dev/null 2>&1 || die "docker compose plugin required"
  parse_up_args "$@"
  compose build
  if [[ "$USE_CADDY" -eq 0 || "$MODE" == "local" ]]; then
    compose up -d marketplace
    echo
    echo "API listening on http://127.0.0.1:8787"
    echo "Health: curl -fsS http://127.0.0.1:8787/v1/health"
    echo "Editor MARKETPLACE_URL=http://127.0.0.1:8787"
  else
    compose --profile proxy up -d
    echo
    print_dns_hint "$HOST" "${DOMAIN:-}" "$MODE"
    echo
    echo "Health (local): curl -fsS http://127.0.0.1:8787/v1/health"
    echo "Public:         https://${HOST}/v1/health  (after DNS propagates)"
  fi
}

cmd_down() {
  need_cmd docker
  [[ -f "$ENV_FILE" ]] || die "missing .env — nothing deployed?"
  compose down
}

cmd_restart() {
  need_cmd docker
  [[ -f "$ENV_FILE" ]] || die "missing .env — run ./deploy.sh local or up first"
  compose build
  local mode="local"
  [[ -f "$STATE_DIR/mode" ]] && mode="$(cat "$STATE_DIR/mode")"
  if [[ "$mode" == "local" ]]; then
    compose up -d marketplace
  else
    compose --profile proxy up -d
  fi
}

cmd_logs() {
  need_cmd docker
  [[ -f "$ENV_FILE" ]] || die "missing .env — run ./deploy.sh up first"
  compose logs "$@"
}

cmd_status() {
  need_cmd docker
  [[ -f "$ENV_FILE" ]] || die "missing .env — run ./deploy.sh up first"
  compose ps
  echo
  if curl -fsS http://127.0.0.1:8787/v1/health; then
    echo
  else
    echo "local health check failed" >&2
  fi
  if [[ -f "$STATE_DIR/host" ]]; then
    echo "configured host: $(cat "$STATE_DIR/host")"
  fi
}

cmd_build() {
  need_cmd docker
  if [[ ! -f "$ENV_FILE" ]]; then
    # minimal env for compose variable substitution
    MARKETPLACE_HOST=localhost ACME_EMAIL= DEV=1
    cat >"$ENV_FILE" <<EOF
MARKETPLACE_HOST=localhost
MARKETPLACE_BASE_DOMAIN=localhost
ACME_EMAIL=
EOF
  fi
  compose build
}

cmd_url() {
  [[ -f "$STATE_DIR/host" ]] || die "run ./deploy.sh up first"
  echo "https://$(cat "$STATE_DIR/host")"
}

case "$CMD" in
  local) cmd_local ;;
  up) cmd_up "$@" ;;
  down) cmd_down ;;
  restart) cmd_restart ;;
  logs) cmd_logs "$@" ;;
  status) cmd_status ;;
  build) cmd_build ;;
  dns-hint) print_dns_hint ;;
  url) cmd_url ;;
  -h|--help|help|"") usage; [[ -n "$CMD" ]] || exit 0 ;;
  *) die "unknown command: $CMD (try --help)" ;;
esac
